# https://pre-commit.com/#creating-new-hooks
- id: prepare-commit-msg
  name: Git Commit AI
  description: A hook to assist with git commit messages using AI.
  entry: prepare-commit-msg.sh
  language: script
  args: ["--commit-msg-filename"]
  stages: [prepare-commit-msg]
  pass_filenames: false
- id: keep-a-changelog
  name: Changelog AI
  description: A hook to assist with updating CHANGELOG.md using AI.
  entry: keep-a-changelog.sh
  language: script
  fail_fast: true
  stages: [pre-commit]
  pass_filenames: false
